expname: nerf_8
basedir: ./logs
datadir: ./data/horns_8
dataset: llff
trainer: nerf

# model
model:
  depth: 8
  width: 256
  xyz_embed_dim: 10  # for positional encoding
  dir_embed_dim: 4  # for positional encoding
  skips: [4]  # add skip connection in the Dth layer

# Hyperparameters
iters: 50000  # total training iterations
lr: 0.0005
momentum: 0.9
weight_decay: 0.0
scheduler:
  decay_step: [30000]
  decay_gamma: 0.1

batch_size: 2048  # number of rays per batch
chunk: 8192  # number of rays processed for inference
N_samples: 64
N_importance: 128
perturb: 1.0
noise_std: 1.0
white_back: false  # use white background for rendering when using blender dataset
gpu: 0
