expname: nerfw
basedir: ./logs
trainer: nerfw

dataset:
  name: phototourism
  root_dir: ./data/phototourism/brandenburg_gate
  resolution: 0.5

# model
model:
  depth: 8
  width: 256
  xyz_embed_dim: 15  # for positional encoding
  dir_embed_dim: 4  # for positional encoding
  app_embed_dim: 48  # for appearance embedding
  tra_embed_dim: 16  # for transient embedding
  beta_min: 0.1  # to control the stability of beta
  lambda_u: 0.01  # regularizer multiplier for loss
  skips: [4]  # add skip connection in the Dth layer

# Hyperparameters
iters: 200000  # total training iterations
lr: 0.001
momentum: 0.9
weight_decay: 0.0
scheduler:
  decay_step: [120000, 160000]
  decay_gamma: 0.1

batch_size: 2048  # number of rays per batch
chunk: 8192  # number of rays processed for inference
N_samples: 128
N_importance: 128
perturb: 1.0
noise_std: 0
white_back: false  # use white background for rendering when using blender dataset
gpu: 0
